### PR TITLE
Switch the build system to Dune

### PR DESCRIPTION
**Pull request by anton-trunov**
Hi, here is my experiment with porting `smart-print`'s build system to Dune. Let me highlight some of the changes in the following summary:

- I guess the most controversial change here is the deprecation of the package name `smart_print` in favor of `smart-print`. The package name is `smart_print` and the corresponding name on opam is `smart-print` which makes Dune unhappy about this discrepancy and it refuses to build the project. I'm happy to learn if there is a better workaround than using Dune's deprecation facilities as in commit 04b225a52a6e63d687fb6d319401e4f6862e0855. By the way, since commit b5b42722963b259a88854a4620dfb5329c4063d7 does not build precisely because of this issue, I think it would be better to squash them if you think this PR is worth merging.

- Then I had to switch to `odoc` (that's what Dune uses to generate documentation, afaik). The entry point to the docs can be found at `_build/default/_doc/_html/index.html`.

- Expectation tests in Dune are very nice. Dune automatically handles `*.expected` files, so no need anymore to call `diff` in `Makefile`.

- I added `--profile release` to `dune` invocations because the documenting comments generate a bunch of warnings 50, e.g. like this one
  ```
  File "smartPrint.mli", line 6, characters 0-17:
  6 | (** {1 Basics} *)
      ^^^^^^^^^^^^^^^^^
  Error (warning 50): unattached documentation comment (ignored)
  ```

### CODE REVIEW

**Comment by clarus** [comment]
Thanks for the work! I did not know about all these Dune tricks. For me it is fine if the library changes its name. Cool for the Dune test system. I will look into that.

**Comment by clarus** [comment]
Thanks! Works perfectly with coq-of-ocaml!

**Comment by clarus** [comment]
Done.

**Comment by anton-trunov** [comment]
Great! Thank you for letting me know :)

**Pull request merged**
